# Base configs
baseurl: "https://billpsomas.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Bill Psomas"
subtitle: "See the world through my eyes!"
author: "Bill Psomas"
header:
 title: "Photography"
 subtitle: "by Bill Psomas"
footer:
 name: "Aloha, my name is Bill"
 bio: "I am a Computer Vision Engineer from Athens. "
social_urls:
  facebook: "https://www.facebook.com/billpsomas24"
  instagram: "https://www.instagram.com/bill_psomas/"
  linkedin: "https://www.linkedin.com/in/bill-psomas/"
  github: "https://github.com/billpsomas"

#footer:
#github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
#web_design: "AJ"

#twitter: "https://www.twitter.com/ram__patra"
#dribbble: "https://dribbble.com/rampatra"