# Base configs
baseurl: "https://billpsomas.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Bill Psomas"
subtitle: "See the world through my eyes!"
author: "Bill Psomas"
header:
 title: "Photography"
 subtitle: "by Bill Psomas"
footer:
 name: "Aloha, my name is Bill"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/billpsomas24"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/bill_psomas/"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/bill-psomas/"
  github: "https://github.com/billpsomas"